### ISSUE TITLE
latest phonemizer unable to run

### ISSUE THREAD

**Issue by jinfagang** [rendchevi/nix-tts#1]
first, it got error in here:

```
phonemizer_backend.phonemize(
                    self._expand_abbreviations(t.lower()),
                    strip=True,
                )
```

latest need a [] of text as input.

And the return of new phoemizer is very strange:

['bˈɔːɹn tə mˈʌltɪplˌaɪ, bˈɔːɹn tə ɡˈeɪz ˌɪntʊ nˈaɪt skˈaɪz.']

it returned something like this.

**Comment by jinfagang** [comment]
I solved it.

**Comment by jinfagang** [comment]
I solved it.

**Comment by JonathanLehner** [comment]
how?
