### ISSUE TITLE
add Gradio web demo/model to Huggingface 

### ISSUE THREAD

**Issue by AK391** [rendchevi/nix-tts#3]
Hi, would you be interested in adding  nix-tts to Hugging Face as a Gradio Demo? I see there is already a streamlit demo and I think having a Gradio version would be cool as well.

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by rendchevi** [comment]
Hi, I haven't tried Gradio yet but the range of controllability seems great. Would definitely consider it, I'd be interested to build a more interactive (streaming) demo of Nix-TTS.
