### ISSUE TITLE
input text to phonemize() is str but it must be list of str

### ISSUE THREAD

**Issue by bmox** [rendchevi/nix-tts#4]
Hi, can you help me. I'm trying this code on google colab  and I'm getting this error message.
---
Your demo code:
`c, c_length, phoneme = nix.tokenize("Born to multiply, born to gaze into night skies.")
`
error:
input text to phonemize() is str but it must be list of str

I change the line like this:
`c, c_length, phoneme = nix.tokenize(["hi"])
`
error:
 'list' object has no attribute 'lower'

**Comment by rendchevi** [comment]
Hi! Turns out the problem comes from the wrong `phonemizer` version, `phonemizer==2.2.1` is the one that should be installed. I've updated the `requirements.txt` too.
